<a href="https://colab.research.google.com/github/Maucho6340/pandas/blob/main/visualizacion_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Visualizaci√≥n de datos con Python: Matplotlib, Seaborn, Plotly**

https://raw.githubusercontent.com/alura-es-cursos/2063-visualizacion-de-datos-con-bibliotecas-de-python/refs/heads/main/inmigrantes_canada.csv

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/canadian_immegration_data.csv')

In [4]:
df.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [6]:
df.shape

(195, 39)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    195 non-null    object
 1   Continent  195 non-null    object
 2   Region     195 non-null    object
 3   DevName    195 non-null    object
 4   1980       195 non-null    int64
 5   1981       195 non-null    int64
 6   1982       195 non-null    int64
 7   1983       195 non-null    int64
 8   1984       195 non-null    int64
 9   1985       195 non-null    int64
 10  1986       195 non-null    int64
 11  1987       195 non-null    int64
 12  1988       195 non-null    int64
 13  1989       195 non-null    int64
 14  1990       195 non-null    int64
 15  1991       195 non-null    int64
 16  1992       195 non-null    int64
 17  1993       195 non-null    int64
 18  1994       195 non-null    int64
 19  1995       195 non-null    int64
 20  1996       195 non-null    int64
 21  1997       195 non-null    int64
 22  1998       195 non-null    int64
 23  1999       195 non-null    int64
 24  2000       195 non-null    int64
 25  2001       195 non-null    int64
 26  2002       195 non-null    int64
 27  2003       195 non-null    int64
 28  2004       195 non-null    int64
 29  2005       195 non-null    int64
 30  2006       195 non-null    int64
 31  2007       195 non-null    int64
 32  2008       195 non-null    int64
 33  2009       195 non-null    int64
 34  2010       195 non-null    int64
 35  2011       195 non-null    int64
 36  2012       195 non-null    int64
 37  2013       195 non-null    int64
 38  Total      195 non-null    int64
dtypes: int64(35), object(4)
memory usage: 59.5+ KB

In [9]:
df.set_index('Country',inplace=True)

In [10]:
df

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,2741,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,7,...,161,140,122,133,128,211,160,174,217,2985
Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,16,9,15,...,91,77,71,64,60,102,69,46,59,1677
Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,32,29,43,...,615,454,663,611,508,494,434,437,407,8598

In [11]:
anos = list(map(str,range(1980,2014)))

In [12]:
anos

['1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [13]:
colombia = df.loc['Colombia',anos]

In [14]:
colombia

1980     266
1981     326
1982     360
1983     244
1984     235
1985     214
1986     257
1987     376
1988     352
1989     439
1990     614
1991     652
1992     582
1993     464
1994     375
1995     371
1996     381
1997     578
1998     929
1999    1306
2000    2259
2001    2965
2002    3283
2003    4318
2004    4566
2005    6424
2006    6535
2007    5357
2008    5452
2009    4652
2010    5218
2011    4366
2012    3741
2013    3631
Name: Colombia, dtype: object

In [17]:
col_dict = {'A√±o':colombia.index.tolist(),
            'Inmigrantes':colombia.values.tolist(),
            }

In [ ]:
col_dict

In [19]:
datos_col = pd.DataFrame(col_dict)

In [22]:
datos_col.tail()

     A√±o  Inmigrantes
29  2009         4652
30  2010         5218
31  2011         4366
32  2012         3741
33  2013         3631